Implement Email and Password Validation
meshnesh/Bright-Events pull request #7
Opened 2017-12-18 08:28 UTC by meshnesh

## What this PR does
* Implement the feedback gotten for challenge 2
* Implement Email verification in user registration
* Implement Email and Password validation when login
* Implement Email verification when user RSVP to an Event
* Implement Tests on Event RSVP
* Implement Tests on email validation and verification in User Registration and Login

2017-12-18 08:41 UTC, betsybeth commented
Follow conventions of creating a good PR.
Good work.

2017-12-20 07:07 UTC, ann-mukundi requested changes
Please squash your commits the next time you do a PR.

2017-12-20 07:07 UTC, ann-mukundi commented on app/views.py
> -class Event(Resource):
Follow pep8 standards, expected 2 two blank lines before the class.

2017-12-20 07:07 UTC, ann-mukundi commented on app/views.py
> +class Event(Resource):
Follow PEP 8 standards

2017-12-20 07:07 UTC, ann-mukundi commented on app/views.py
> +            print(user)
Remove print statement

2017-12-20 07:07 UTC, ann-mukundi commented on app/views.py
>  class PasswordRest(Resource):
PEP 8. Typo in classname.

2017-12-20 07:07 UTC, ann-mukundi commented on test/tests.py
> +        self.assertEqual(res.status_code, 200)
Code 200 does not necessarily imply that all events have been returned. For instance if you had two events and only one was returned the code would still be the same.

2017-12-20 07:07 UTC, ann-mukundi commented on test/tests.py
>  class TestUsers(unittest.TestCase):
By lumping all your tests together you run the risk of having a test file that is too long. It is better to have each module's tests in a separate file.

2017-12-20 07:07 UTC, ann-mukundi commented on test/tests.py
> +    def test_user_reg_email_exist(self):
I am having a hard time understanding what this is supposed to be testing. Is the goal to check whether a user can register with an already registered email? If thats the case a status code 404 does not seem right as the email actually exists.

2017-12-20 07:07 UTC, ann-mukundi commented on test/tests.py
> +    def test_reg_email_not_exist(self):
Again here, the docstrings don't help me understand what you are testing as they are the same as those in <b> test_user_reg_email_exist </b>

2017-12-20 07:07 UTC, ann-mukundi commented on test/tests.py
>      def test_user_login(self):
It's great to see you test happy scenarios, I'd love to see more sad scenarios tested such as:
<ul>
<li>User login fails if required values are missing</li>
<li>User login fails if a n unregistered email is used</li>
<li>User login fail if wrong password is provided</li>
</ul>

2017-12-21 10:31 UTC, merged